config/routes.rb
Rails.application.routes.draw do

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  get "about", to: "home#about"
  get "sign_up", to:"registration#new"
  post "sign_up", to: "registration#create"
  delete "logout", to: "sessions#destroy"

  get "sign_in", to:"sessions#new"
  post "sign_in", to: "sessions#create"

  get "contact", to: "contact_form#new"
  resources :contact_form, only: %i[new create]

  resource :session
  resource :password
  resource :registration
  resource :password_reset



  # resources :tweets, except: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_form.rb
class ContactForm < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
# password:string virtual
# password_confirmation:string virtual
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true,format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
  normalizes :email, with: ->(email) {email.strip.downcase}

  # has_many: tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :user_signed_in

  def authenticate_user_from_session
    User.find_by(session[:user_id])
  end

  def user_signed_in
    current_user.present?
  end
  helper_method :user_signed_in

  def login(user)
    Current.user =user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/contact_form_controller.rb
# class ContactFormController < ApplicationController
#   def create
#     @name = params[:contact_form][:name]
#     @email = params[:contact_form][:email]
#     @message = params[:contact_form][:message]

#     # Perform any necessary actions with the form data
#     flash[:success] = "Thank you for your message, we will contact you soon"
#     # redirect_to root_path
#   end
# end

class ContactFormController < ApplicationController
  def create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
      flash[:success] = "Thank you for your message, we will contact you soon"
      # Redirige a donde desees después de enviar el formulario
      # redirect_to root_path
    else
      render :new
    end
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
  end
  def about
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id #sign in the user
      redirect_to root_path, notice: "Account created successfully"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user
      # session[:user_id] = @user.id #sign in the user
      redirect_to root_path, notice: "Account created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password_confirmation])
      session[:user_id] = user.id
      redirect_to root_path, notice:"Logged in succesfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/contact_form/new.html.erb
<div class="container mt-4 mb-3">
    <h1 class="fs-1 border-bottom border-secondary py-3">Contact Us</h1>
</div>
<%= form_with scope: :contact_form, url: contact_form_index_path, method: :post, local: true, class: "container" do |form| %>
<div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control mb-3 bg-transparent border-secondary-subtle text-white" %>
</div>
<div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control mb-3 bg-transparent border-secondary-subtle text-white" %>
</div>
<div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, class: "form-control mb-3 bg-transparent border-secondary-subtle text-white" %>
</div>
<%= form.submit "Submit",id: "liveToastBtn", class: "fw-semibold btn btn-primary bg-white text-black border-secondary-subtle" %>
<% end %>

<% flash.each do |key, value| %>
<div class="my-3 bg-transparent text-white border-secondary alert alert-<%= key %>" onclick="">
    <%= value %>
</div>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/home/_header.html.erb
<div class="sidebar">
    <div class="logo_content">
        <div class="logo">
            <%= link_to "Y", root_path, class:"links_name logo_name text-white text-decoration-none"%>
            <%# <a href="/" class="logo_name text-white text-decoration-none">
                <span class="links_name">Y</span>
            </a> %>
            <%# <div class="logo_name">Y</div> %>
        </div>
        <%# <i class='bx bx-menu' id="btn"></i> %>
    </div>
    <ul class="nav_list">
        <li>
            
            <a href="/" class="home">
                <i class='bx bx-home'></i>
                <span class="links_name">Home</span>
            </a>
            <%# <span class="tooltip"></span> %>

        </li>
        <li>
            <a href="/about">
                <i class='bx bx-user'></i>
                <span class="links_name">About Us</span>
            </a>
            <%# <span class="tooltip"></span> %>
            
        </li>
        <li>
            <a href="/contact">
                <i class='bx bx-help-circle' ></i>
                <span class="links_name">Contact Us</span>
            </a>
            <%# <span class="tooltip"></span> %>
        </li>
        
    </ul>
    <div class="profile_content">
        <div class="profile">
            <div class="profile_details">
                <div class="name_username">
                    <% if @user%>
                        <div class=" name text-white-50 fw-light">
                            <%= @user.email%>
                        </div>
                        <i class='bx bx-log-out' id="log_out"></i>
                    <% else%>
                    <div class="login ">
                        <%= link_to "Log in", sign_up_path, class:"ps-4 text-white text-decoration-none fw-light"%>
                    </div>
                    <%end%>
                    <%# <div class="name">Carolina</div> %>
                    <%# <div class="username">  </div> %>
                </div>
            </div>
            
        </div>
    </div>
</div>

//<%=button_to "Log out", logout_path, method: :delete, class:"ps-2 text-white text-decoration-none fw-light bg-transparent border-0"%>

app/views/home/about.html.erb
<div class="about">
    <div class="container">
        <h1 class="fs-1 border-bottom border-secondary py-3">About Us</h1>
        <h2 class="fs-3 mt-4">Who we are</h2>
        <p class="mt-3 text-white/50 font-bold text-2xl p-1">
            We are building the world's most trusted public town square, 
            and we pride ourselves on our commitment to protecting free 
            speech within the boundaries of law.
        </p>
        <p class="mt-3 text-white/50 font-bold text-2xl p-1">
            Beyond that, we aim to increase unregretted user minutes on our platform, 
            and make it the best place on the internet for creators to share content 
            and make money.
        </p>
        <p class="mt-3 text-white/50 font-bold text-2xl p-1">
            Join us to have real impact on what is bound to evolve into the ultimate 
            everything app.
        </p>

        <h2 class="fs-3 mt-4">Our priority</h2>
        <p class="mt-3 text-white/50 font-bold text-2xl p-1">
            Our commitment to serve the public conversation is also a 
            commitment to protect the information you share with us and
            to provide meaningful privacy controls. Transparency matters 
            to us, so we want you to know what data we collect, how we use it, 
            when we share it, and what we do to protect it.
        </p>
    </div>
</div>

app/views/home/index.html.erb
<div class="container mt-4">
    <h1 class="fs-1 border-bottom border-secondary py-3">Home</h1>
    <p class="fs-5">What's happening?</p> 

    <% if @user%>
        <div class="text-white-50 fw-light">
            Logged in as <%= @user.email%>
        </div>
        <%=button_to "Log out", logout_path, method: :delete%>
    <%end%>

    
</div>

app/views/layouts/_footer.html.erb

<footer class=" bd-footer py-4 py-md-5 ">
  <div class="bg-black container py-4 py-md-5 px-4 px-md-3 text-body-secondary" style="--bs-bg-opacity: .4;">
    <div class="row">

      <div class="col col-sm-3 mb-3">
        <ul class="list-unstyled small">
          <li class="text-center mb-2 text-white ">Y- &copy;2024</li>
        </ul>
      </div>

      <div class="col-6 col-lg-4 mb-3 text-center">
        <ul class="list-unstyled px-4 d-flex md">
          <li class="col mb-2 mx-2 link-offset-2"><a class="link-light link-underline-opacity-0" href="#">Terms of Use</a></li>
          <li class="col mb-2 mx-2 link-offset-2"><a class="link-light link-underline-opacity-0" href="#">Privacy Policy</a></li>
        </ul>

        <ul class="list-unstyled px-4 d-flex md" >
            <li class="col mb-2 mx-2 link-offset-2" ><a class="link-light link-underline-opacity-0" href="/contact">Contact Us</a></li>
            <li class="col mb-2 mx-2 link-offset-2" ><a class="link-light link-underline-opacity-0" href="#">Facebook</a></li>
            <li class="col mb-2 mx-2 link-offset-2" ><a class="link-light link-underline-opacity-0" href="#">Instagram</a></li>
        </ul>
      </div>
      
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Y</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= stylesheet_link_tag "main" %>
		<%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
		<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
	</head>

	<body>
		<%= render partial: 'home/header' %>
		<%if user_signed_in%>
			<%=link_to "Edit Password", edit_password_path%>
			<%=button_to "Log out", session_path, method: :delete%>
		<%else%>
			<%=link_to "Sign Up", new_registration_path%>
			<%=link_to "Log in", new_session_path%>
		<%end%>

		<div class="home_content container">
			<%= yield %>
			<%= render 'layouts/footer'%>
			<% debug(params) if Rails.env.development?%>
		</div>
		
	</body>
</html>